# Nexus server nginx configuration file
events {
    worker_connections 4096; ## Default: 1024
}
http {
    sendfile                on;
    tcp_nopush              on;
    tcp_nodelay             on;
    keepalive_timeout       65s;
    types_hash_max_size     2048;

    include "C:/Program Files/ANSYS Inc/v261/CEI/apex261/machines/win64/nginx/conf/mime.types";
    default_type application/octet-stream;

    upstream localhost {
        least_conn;
        server 127.0.0.1:35488;
    }

    server {
        server_name 127.0.0.1;
        #access_log off;
        listen 15688;
        proxy_read_timeout 300s;
        keepalive_timeout 90s;
        client_max_body_size 5000M;
        client_header_buffer_size 4096k;
        location /media/ {
            root "D:/generic_fan_case_Achilleas/Pyfluent/project_axial_fan.cffdb/axial_fan-Solve/Simulation_Reports";
        }
        location /static/ {
             root "C:/Program Files/ANSYS Inc/v261/CEI/nexus261/django";
        }
        location /ansys261/ {
             root "C:/Program Files/ANSYS Inc/v261/CEI/nexus261";
        }
        location /ansys/ {
             try_files $uri $uri/ @ansys261;
        }
        location @ansys261 {
             rewrite ^/ansys(/.*)$ /ansys261$1 last;
        }
        location / {
             proxy_pass http://localhost;
             proxy_pass_request_headers on;
             proxy_set_header X-Forwarded-Host $host:$server_port;
             proxy_set_header X-Forwarded-Proto $scheme;
        }

    }
}
